export { default as Hero } from './Hero'
export { default as Features } from './Features'
export { default as WhyUs } from './WhyUs'
export { default as OurWorks } from './OurWorks'
export { default as LogoCloud } from './LogoCloud'
export { default as LatestBlog } from './LatestBlog'
export { default as Cta } from './Cta'
export { default as PageHero } from './PageHero'